import { weaponById } from './content';
import { defeatAdvice } from './defeat';
import { enemyPortrait } from './plush';
import type { Game } from './engine';
export function defeatPanel(game: Game, payout:{gold:number;xp:number}, practice:boolean) {
 const point=game.retryPoint,receipt=game.damageLog.at(-1),advice=defeatAdvice(receipt),source=receipt?.source;
 const portrait=enemyPortrait(source?.kind==='enemy'?source.enemy:'raider',game.config.region);
 return `<div class="modal-backdrop"><section class="modal defeat-modal" aria-label="Defeat report"><div class="defeat-heading"><p class="eyebrow">OFFICIAL INCIDENT REPORT · TAKE ${game.retries+1}</p><h2>Restuff. Get even.</h2></div><div class="defeat-grid"><aside class="culprit-card"><span class="culprit-stamp">WANTED FOR UNSTUFFING</span><img src="${portrait}" alt="${source?.kind==='enemy'?advice.culprit:'Molar, incident-report clerk'}"/><strong>${advice.culprit}</strong><span>${receipt?`Final hit: −${receipt.amount} stuffing`:'Last seen making terrible choices'}</span></aside><div class="retry-plan"><div class="counter-note"><p class="eyebrow">NEXT TIME, TRY THIS</p><p>${advice.tip}</p></div><div class="encounter-trail" aria-label="Encounter progress">${game.encounters.map((e,i)=>`<span class="${i<game.wave?'done':i===game.wave?'current':''}" title="${e.title}">${i<game.wave?'✓':i+1}</span>`).join('')}<small>${Math.max(0,game.wave)} / ${game.encounterCount} fights cleared</small></div>${point?`<button class="primary full" data-action="retry-fight">Retry this fight <span>↻</span></button><p class="checkpoint-detail">${point.title}<br>Restores ${point.hp.join(' / ')} stuffing and your gear at fight start.<br>Failed-fight loot resets. Cleared fights stay cleared.</p>`:''}<div class="defeat-exit"><button class="secondary" data-action="cash-out">${practice?'Leave practice':'Bank defeat & return to camp'}</button><button class="text-button" data-action="retry">Restart chapter</button></div><p class="bank-explanation loss-loot">${game.foundWeapons.length?`Found: ${game.foundWeapons.map(id=>weaponById(id).name).join(' · ')}. `:''}${practice?'Practice never changes your saved progress.':`Leaving now banks ${payout.xp} XP, keeps found weapons, and loses the loose teeth. Retries bank nothing yet.`}</p></div></div><p class="retry-footnote">${game.retries} fight retries · ${game.kills} foes defeated · ${game.bestCombo}× best combo · Third star requires a fast clear without retries.</p></section></div>`;
}
