import { WORKPLACES } from './sabotage';
import { BESTIARY, REGIONS, type EnemyKind } from './content';
import { TRAP_NAMES, type TrapKind } from './setpieces';
export type DamageSource = { kind: 'enemy'; enemy: EnemyKind; region: number; attack?: 'rush' | 'shot' | 'wave' | 'swat' | 'read-heavy' } | { kind: 'machine'; machine: TrapKind; supply?: boolean } | { kind: 'sabotage'; region: number } | { kind: 'vent' } | { kind: 'blast' };
export interface DamageReceipt { source: DamageSource; amount: number; at: number; player: number }
export function defeatAdvice(receipt?: DamageReceipt) {
  if (!receipt) return { culprit: 'A sequence of terrible decisions', tip: 'Read the wind-up, dodge the hit, then attack during recovery.' };
  const s=receipt.source;
  if(s.kind==='enemy'&&s.attack==='read-heavy')return {culprit:'Your predictable Heavy spam',tip:'The red ring warns of a close counter. Jump or get clear; use connected Light combos, aerial attacks or the rear before another Heavy.'};
  if(s.kind==='sabotage')return {culprit:WORKPLACES[s.region].name,tip:WORKPLACES[s.region].dodge + '. The bell starts a single disaster; bait the crew into its marked path.'};
  if(s.kind==='vent')return {culprit:'A public fart',tip:'The floor vent erupts in pulses. Jump over the fumes or change lanes.'};
  if(s.kind==='blast')return {culprit:'An extremely rude explosion',tip:'Leave the marked blast circle before its fuse finishes. A jump can clear a low blast.'};
  if(s.kind==='machine'&&s.supply)return {culprit:'The complimentary benefits booth',tip:s.machine==='press'||s.machine==='stamp'?'The booth’s press catches jumps. Wait beside its marked bay, then step in and bonk the open shutter. The main road is safe to pass.':'The booth closes during its low hazard. Jump out or wait beside the marked bay, then get close and bonk the open shutter. Supplies are optional.'};
  if(s.kind==='machine')return {culprit:TRAP_NAMES[s.machine],tip:s.machine==='press'||s.machine==='stamp'?'Overhead machinery catches jumps. Move to another lane during the yellow warning, or bonk its shutdown switch.':s.machine==='cutter'?'The cutter sweeps along the whole marked corridor. Jump across or leave its lane; the shutdown lever stops it.':s.machine==='drain'?'The drain pulls during its warning. Jump or dodge out, then bait an enemy over it.':s.machine==='taffy'?'Syrup slows your feet before it erupts. Jump or dodge out before the warning ends.':'Jump the spore burst or take another lane. Its switch is further along the road.'};
  if(s.enemy==='boss')return {culprit:REGIONS[s.region].boss,tip:[ 'Step between the burp volleys. When the kettle lands or finishes belching, punish its recovery.', 'Falling ice catches jumps. Change lanes before it lands, then close in when the volley finishes.', 'During inhale, Heavy a laundry bundle into the open drum. Back away during the spin.', 'Jump the low sweets, then leave the marked lane before the dentures snap. His wafer body opens afterward; aerial head hits are riskier during the serving.', 'His front is armored; circle behind or attack while he is dizzy. Jump low forks, but leave the lane when he raises them.', 'His staff carry the royal protection. Clear them, or bowl one into him for a longer opening. Sidestep the overhead stamp; jumping cannot clear it.' ][s.region]};
  const culprit=BESTIARY.find(e=>e.kind===s.enemy)?.name ?? s.enemy;
  if(s.attack==='wave')return {culprit,tip:'That shockwave hugs the floor. Jump over it and land beside the brute, not in front of its next swing.'};
  if(s.attack==='swat')return {culprit,tip:'The brute aimed high because you were airborne. Change lanes instead of repeating the same jump.'};
  const tips:Record<Exclude<EnemyKind,'boss'>,string>={raider:'The rat crouches before pouncing. Dodge across its path, then punish the landing.',archer:'The mosquito aims at your current position and height. Change lanes after the aim; chase it between shots.',brute:'Planted fists resist frontal interruption. Get behind it, land Light ×2 → Heavy, or bowl another enemy into it. You can also evade the swing and punish the opening.',shield:'Frontal light attacks hit the lid. Use Heavy or move behind the crab; dodge its riposte.',bomber:'The tick retches two stink sacs. Jump or leave the circles, or punt a sac with grounded Light before its fuse ends. The second sac still needs an answer.',charger:'The boar commits to a straight rush. Step into another lane, then attack its exposed recovery.',healer:'Heavy or power cuts the jelly’s green stitch. Pull or bowl its patient away to break the thread. Alone, its tentacle slap can be jumped or sidestepped.',flanker:'The centipede runs around your side before dashing. Track its warning and punish the end of the dash.'};
  return {culprit,tip:tips[s.enemy]};
}
