import type { HeroId } from './content';
export interface StoryLine { speaker:'clerk'|'hero'|'boss'; text:string }
export interface ChapterStory { title:string; task:string; intro:StoryLine[]; after:StoryLine[] }
const say=(speaker:StoryLine['speaker'],text:string):StoryLine=>({speaker,text});
export const PROLOGUE:StoryLine[]=[
 say('clerk','By royal decree: the crown has lost six teeth. Until they return, every citizen owes a monthly stuffing tax.'),
 say('hero','That sounds like a king problem. We are busy being banned from a picnic.'),
 say('clerk','Recover the teeth and receive a lifetime buffet pass. The word “lifetime” has been reviewed by our lawyers.'),
 say('hero','A terrible offer. We accept immediately.')
];
export const CHAPTER_STORY:ChapterStory[]=[
 {title:'A picnic worth committing crimes for',task:'Cross the woods. Find the kettle hoarding the first crown tooth.',intro:[say('clerk','Sir Burps-a-Lot bought the first tooth to open stubborn pickle jars.'),say('hero','Finally. A villain with a practical reason.'),say('clerk','His rats have occupied the picnic road. Please return fewer rats than you found.')],after:[]},
 {title:'The kettle calls you disgusting',task:'Dodge the burp volley. Hit Sir Burps-a-Lot while he recovers.',intro:[say('boss','YOU ARE NOT ON THE GUEST LIST.'),say('hero','We brought a spatula and a catastrophic digestive condition.'),say('boss','Fine. But no outside food.')],after:[say('boss','Take the tooth. My lid has become a percussion instrument.'),say('clerk','One tooth! The king says your buffet pass now covers looking at soup.')]},
 {title:'Cold feet. Worse decisions.',task:'Get through Frostfall Pass and reach the freezer.',intro:[say('clerk','The second tooth is frozen inside a doughman. Nobody knows why he has a mortgage.'),say('hero','Do we hit him until the economics come out?'),say('clerk','That is the official royal policy.')],after:[]},
 {title:'Dough not resuscitate',task:'Escape the falling ice circles. Punish the Doughman between volleys.',intro:[say('boss','I HAVE BEEN PROOFING FOR THREE HUNDRED YEARS.'),say('hero','You smell like a wet glove with ambitions.'),say('boss','THAT IS MY STARTER.')],after:[say('clerk','Two teeth. The king has charged you a thawing fee.'),say('hero','We are beginning to suspect the buffet is a metaphor for getting screwed.')]},
 {title:'The missing sock is unionizing',task:'Escort the witness hamper through the marsh and follow the laundry trail.',intro:[say('clerk','Madame Spin-Cycle swallowed tooth three with a sock. Her warranty does not cover royalty.'),say('hero','Our warranty expired when Bram grew a second opinion.'),say('clerk','Deliver the witness hamper. Those socks saw too much. Mostly Bram.')],after:[]},
 {title:'Delicates. Violence. Repeat.',task:'Heavy a laundry bundle into the open drum, then attack while jammed.',intro:[say('boss','INSERT COIN. REMOVE DIGNITY.'),say('hero','We only have loose teeth and a son nobody wanted.'),say('boss','DO NOT MIX COLOURS. DO NOT MIX FEELINGS.')],after:[say('clerk','Three teeth! Also, a sock with the king’s initials on it.'),say('hero','He sent his own laundry debt collectors after us? That absolute bath mat.')]},
 {title:'Everything is edible once',task:'Cross the candy works. Keep moving between the staggered bomb circles.',intro:[say('clerk','Count Snackula has tooth four. The royal sugar tax pays his entire army.'),say('hero','So we are paying the guys trying to kill us?'),say('clerk','Only the permanent employees. The ticks are contractors.')],after:[]},
 {title:'A hostile snackquisition',task:'Avoid the Count’s bomb spread. Strike after the feast of explosions.',intro:[say('boss','I VANT TO SUCK YOUR—'),say('hero','Do not finish that sentence. We are already disappointed.'),say('boss','—DISCRETIONARY INCOME.')],after:[say('boss','The king sold me that tooth. He said heroes would bring the rest back for free.'),say('hero','We have been employed. This is the worst thing that has ever happened to us.')]},
 {title:'Occupational health and savagery',task:'Push through the junkyard and find the king’s shipping manifest.',intro:[say('clerk','Forklift Frank shipped all six teeth. The manifest says “manufacture a crisis”.'),say('hero','We manufacture gases. His business model is somehow worse.'),say('clerk','Take the fifth tooth. I am updating my résumé.')],after:[]},
 {title:'No paid breaks',task:'Leave Frank’s charge lane. Attack when the forklift is dizzy.',intro:[say('boss','YOU CANNOT COME IN WITHOUT A HIGH-VIS VEST.'),say('hero','We are on fire. That should count.'),say('boss','... I WILL ASK MY SUPERVISOR WHILE RUNNING YOU OVER.')],after:[say('clerk','Five teeth. The manifest says the king kept the last one as “executive compensation”.'),say('hero','Time to compensate him with a very large fork.')]},
 {title:'The cardboard coup',task:'Climb the keep. Break the royal debt collectors and their healers.',intro:[say('clerk','The crown makes obedient monsters out of discarded rubbish. He was never saving the kingdom.'),say('hero','We are discarded rubbish with terrible attitudes. His system has a flaw.'),say('clerk','I quit. The buffet is real, by the way. He has been eating there alone.')],after:[]},
 {title:'Bite the hand that invoices you',task:'Survive the royal summons and volleys. Finish the king during recovery.',intro:[say('boss','WELCOME, VALUED INDEPENDENT CONTRACTORS.'),say('hero','We have a complaint about the dental plan.'),say('boss','YOUR COMPLAINT HAS BEEN AUTOMATICALLY CLOSED.')],after:[say('boss','You cannot abolish the stuffing tax. I have a very expensive hat.'),say('hero','We can. And your hat is now a public toilet brush.'),say('clerk','The crown became a free dental clinic. The buffet opened to everyone.'),say('hero','Ash set the soup on fire. Wren froze the bill. Bram’s son ate the suggestion box.'),say('clerk','For the first time in years, the kingdom was a complete mess for the right reasons.')]} 
];
export function storyLines(stage:number,kind:'intro'|'after',hero:HeroId):StoryLine[]{
 const lines=kind==='intro'&&stage===0?[...PROLOGUE,...CHAPTER_STORY[stage].intro]:CHAPTER_STORY[stage][kind];
 return lines.map(line=>line.speaker==='hero'&&hero==='moss'&&line.text==='Finally. A villain with a practical reason.'?{...line,text:'My son also opens jars. Mostly from the inside.'}:line.speaker==='hero'&&hero==='frost'&&line.text==='Finally. A villain with a practical reason.'?{...line,text:'I licked a frozen jar once. We are still legally married.'}:line);
}
export const validStoryId=(id:unknown):id is string=>typeof id==='string'&&/^(intro|after)-(?:[0-9]|1[01])$/.test(id);
